---
baseurl: "http://khoapham.me"
canonifyurls: true
contentdir: "content"
languageCode: "en-us"
layoutdir: "layouts"
publishdir: "public"
Title: "Khoa Pham"

Params:
    Author: "Khoa Pham"
    Description: "Khoa Pham is a senior web developer focusing on writing clean code and developing good UX with technologies like Golang, Rails, EmberJS, and Postgres"
    TwitterHandler: "@pmkhoa"
    AuthorImage: "https://avatars0.githubusercontent.com/u/1144585"
    GooglePlus: "https://plus.google.com/103713398374675106375/"
    Keywords: "Khoa Pham, web developer, frontend developer, UX, UI, web developer Portland"
    ShowRelatedPost: false
    SiteName: "Khoa Pham"

MetadataFormat: "yaml"
---
