---
baseurl: "http://www.khoapham.me"
canonifyurls: true
contentdir: "content"
languageCode: "en-us"
layoutdir: "layouts"
publishdir: "public"
title: "Khoa Pham"

Params:
    ShowRelatedPost: true

MetadataFormat: "yaml"
---
